# This release process looks for dim tags and produces releases
# build on the version number.
name: release

on:
  push:
    tags:
      - 'go-maven-poller-[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract current maven version
      run: echo "::set-output name=version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)"
      id: version
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: go-maven-poller-plugin.jar
        path: target/go-maven-poller-plugin.jar
    - uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/go-maven-poller-plugin.jar
        asset_name: go-maven-poller-plugin.jar
        asset_content_type: application/java-archive
